### PR TITLE
Supoort conversion of numerically-index objects to arrays

### PR DESCRIPTION
**Pull request by lune-sta**
I tried to implement conversion of numerically-index objects to arrays.
Tell me if there's even a little mistake. 

https://github.com/lightbend/config/blob/master/HOCON.md#conversion-of-numerically-indexed-objects-to-arrays

### CODE REVIEW

**Comment by darthbear** [comment]
Thanks @lune-sta for your PR!

**Comment by darthbear** [comment]
Thanks @lune-sta for your contribution. Your fix was pushed to `pyhocon==0.3.48`

**Comment by lune-sta** [comment]
@darthbear Thank you for the merge!
Please also check the "Conversion of numerically-index objects to arrays" status in README :)

**Comment by darthbear** [comment]
Thank you! 👍 I just did!

**Pull request merged**
