### PR TITLE
fix(#324): avoid parsing improperly periods on several lines with recent pyparsing versions

### PR DESCRIPTION
**Pull request by pierresouchay**
periods were not correctly parsed with recent versions of pyparsing because of usage of White()

White is actually not needed, added some tests to avoid issues detected in #324

### CODE REVIEW

**Comment by pierresouchay** [comment]
Hello @darthbear ,

Could you consider this change as it broke with recent pyparsing releases?

**Comment by pierresouchay** [comment]
@darthbear Thank you!

**Comment by darthbear** [comment]
Thanks for your contribution @pierresouchay! Released new version 0.3.61

**Comment by pierresouchay** [comment]
Thank you so much @darthbear !

**Pull request merged**
